# Generated by Django 3.1.1 on 2020-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20201020_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedtls',
            name='ConMob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedtls',
            name='ConNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
