# Generated by Django 3.1.1 on 2020-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_auto_20201020_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedtls',
            name='ConNum',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
