# Generated by Django 3.1.1 on 2020-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20201020_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedtls',
            name='InvDtls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedtls',
            name='LocName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedtls',
            name='PumpDtls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
